(function(g){var window=this;var Kpa=function(a,b){return g.Ub(a,b)},h5=function(){},Lpa=function(a){if(a.yc&&"function"==typeof a.yc)return a.yc();
if(g.v(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},Mpa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.v(a))(0,g.B)(a,b,void 0);else{if(a.Dd&&"function"==typeof a.Dd)var c=a.Dd();else if(a.yc&&"function"==typeof a.yc)c=void 0;else if(g.La(a)||g.v(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=Lpa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},i5=function(a){g.bn(a,"zx",g.dd());
return a},j5=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.gn(a.l,b,c)},k5=function(a){return(a=g.Bo(a))?new ActiveXObject(a):new XMLHttpRequest},l5=function(a,b){return b+" ["+a.aa+" "+a.F+" "+a.getStatus()+"]"},Npa=function(a){return"content-type"==a.toLowerCase()},m5=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.B&&(g.w.clearTimeout(a.B),a.B=null)},Opa=function(a){return g.Od&&g.qd(9)&&g.Fa(a.timeout)&&g.Ca(a.ontimeout)},n5=function(a){a.O||(a.O=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},o5=function(a,b){if(a.g){m5(a);
var c=a.g,d=a.P[0]?g.Ha:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},p5=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;n5(a);o5(a)},q5=function(a){return a.g?a.g.readyState:0},r5=function(a){if(a.i&&"undefined"!=typeof g.nY)if(a.P[1]&&4==q5(a)&&2==a.getStatus())l5(a,"Local request error detected and ignored");
else if(a.D&&4==q5(a))g.Jg(a.Rv,0,a);else if(a.dispatchEvent("readystatechange"),4==q5(a)){l5(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Tg(String(a.F))[1]||null;if(!f&&g.w.self&&g.w.self.location){var k=g.w.self.location.protocol;f=k.substr(0,k.length-1)}e=!Ppa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<q5(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";n5(a)}}finally{o5(a)}}},s5=function(a){g.Uf.call(this);
this.headers=new g.Rm;this.M=a||null;this.i=!1;this.P=this.g=null;this.aa=this.F="";this.u=0;this.l="";this.o=this.V=this.D=this.O=!1;this.A=0;this.B=null;this.Y="";this.I=this.R=!1},t5=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},Qpa=function(a,b){var c=[];
g.Rk(b,function(d){try{var e=g.Qo.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ca(e)?g.Po(e)&&c.push(d):c.push(d)},a);
return c},Rpa=function(a,b){var c=Qpa(a,b);
(0,g.B)(c,function(d){g.Qo.prototype.remove.call(this,d)},a)},u5=function(a){if(a.Yc){if(a.Yc.locationOverrideToken)return{locationOverrideToken:a.Yc.locationOverrideToken};
if(null!=a.Yc.latitudeE7&&null!=a.Yc.longitudeE7)return{latitudeE7:a.Yc.latitudeE7,longitudeE7:a.Yc.longitudeE7}}return null},Spa=function(a,b){g.Za(a,b)||a.push(b)},v5=function(a){var b=0,c;
for(c in a)b++;return b},w5=function(a,b){var c=b instanceof g.xc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},Tpa=function(a){return/^\s*$/.test(a)?!1:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,""))},Upa=function(a){try{return g.w.JSON.parse(a)}catch(b){}a=String(a);
if(Tpa(a))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Vpa=function(a,b,c,d){var e=new g.Um(null,void 0);
a&&g.Vm(e,a);b&&g.Wm(e,b);c&&g.Xm(e,c);d&&(e.i=d);return e},x5=function(a){if(g.w.JSON)try{return g.w.JSON.parse(a)}catch(b){}return Upa(a)},y5=function(){this.g=[];
this.i=[]},z5=function(a,b){g.Vp[a]=!0;
var c=g.Tp();c&&c.publish.apply(c,arguments);g.Vp[a]=!1},A5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Rm;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Wpa(this,a.capabilities||""),Xpa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},Wpa=function(a,b){a.capabilities.clear();
(0,g.$d)(b.split(","),g.Qa(Kpa,Ypa)).forEach(function(c){a.capabilities.add(c)})},Xpa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},B5=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},C5=function(a,b){return!!b&&(a.id==b||a.uuid==b)},D5=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Zpa=function(a){return new B5(a)},E5=function(a){return g.Ka(a)?(0,g.G)(a,Zpa):[]},F5=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},G5=function(a){return g.Ka(a)?"["+(0,g.G)(a,F5).join(",")+"]":"null"},H5=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},$pa=function(a){return(0,g.G)(a,function(b){return{key:b.id,
name:b.name}})},I5=function(a,b){return g.Wa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},J5=function(a,b){return g.Wa(a,function(c){return C5(c,b)})},aqa=function(){var a=(0,g.kt)();
a&&Rpa(a,a.g.cf(!0))},K5=function(){var a=g.nt("yt-remote-connected-devices")||[];
g.pb(a);return a},bqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(d,e){return 0==e?d:d.substring(c.length)})},L5=function(a){g.mt("yt-remote-connected-devices",a,86400)},N5=function(){if(M5)return M5;
var a=g.nt("yt-remote-device-id");a||(a=H5(),g.mt("yt-remote-device-id",a,31536E3));for(var b=K5(),c=1,d=a;g.Za(b,d);)c++,d=a+"#"+c;return M5=d},O5=function(){var a=K5(),b=N5();
g.Za(a,b);g.pt()&&g.rb(a,b);a=bqa(a);if(0==a.length)try{g.Ms("remote_sid")}catch(c){}else try{g.Ls("remote_sid",a.join(","),-1)}catch(c){}},P5=function(){return g.nt("yt-remote-session-browser-channel")},Q5=function(){return g.nt("yt-remote-local-screens")||[]},R5=function(){g.mt("yt-remote-lounge-token-expiration",!0,86400)},cqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(Q5(),function(d){return d.loungeToken}),c=(0,g.G)(a,function(d){return d.loungeToken});
(0,g.hj)(c,function(d){return!g.Za(b,d)})&&R5();
g.mt("yt-remote-local-screens",a,31536E3)},dqa=function(a,b){g.mt("yt-remote-session-browser-channel",a);
g.mt("yt-remote-session-screen-id",b);var c=K5(),d=N5();g.Za(c,d)||c.push(d);L5(c);O5()},S5=function(a){a||(g.ot("yt-remote-session-screen-id"),g.ot("yt-remote-session-video-id"));
O5();a=K5();g.bb(a,N5());L5(a)},U5=function(){if(!T5){var a=g.$o();
a&&(T5=new g.Ko(a))}return T5?!!T5.get("yt-remote-use-staging-server"):!1},V5=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},W5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},Y5=function(a){a.length?X5(a.shift(),function(){Y5(a)}):Z5()},eqa=function(a){return"chrome-extension://"+a+$5},X5=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},Z5=function(){var a=W5();
a&&a(!1,"No cast extension found")},a6=function(){if(fqa){var a=2,b=W5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;X5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",Z5,c)}},gqa=function(){a6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);Y5(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+$5,"//www.gstatic.com/eureka/clank"+$5])},b6=function(a,b,c){g.H.call(this);
this.A=null!=c?(0,g.y)(a,c):a;this.Uc=b;this.u=(0,g.y)(this.MC,this);this.g=!1;this.i=0;this.l=this.za=null;this.o=[]},c6=function(){},d6=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.ba=new g.hn(this);this.i=new g.Ig;this.i.setInterval(250)},f6=function(a,b,c){a.Ph=1;
a.cg=i5(b.clone());a.mh=c;a.u=!0;e6(a,null)},g6=function(a,b,c,d,e){a.Ph=1;
a.cg=i5(b.clone());a.mh=null;a.u=c;e&&(a.Iz=!1);e6(a,d)},e6=function(a,b){a.si=(0,g.D)();
h6(a);a.wg=a.cg.clone();j5(a.wg,"t",a.A);a.Mk=0;a.tc=a.g.kp(a.g.Dk()?b:null);0<a.Pp&&(a.pn=new g.Cl((0,g.y)(a.QA,a,a.tc),a.Pp));a.ba.da(a.tc,"readystatechange",a.sL);var c=a.Rg?g.bc(a.Rg):{};a.mh?(a.Yn="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.tc.send(a.wg,a.Yn,a.mh,c)):(a.Yn="GET",a.Iz&&!g.Qd&&(c.Connection="close"),a.tc.send(a.wg,a.Yn,null,c));a.g.ne(1)},o6=function(a,b,c){for(var d=!0;!a.Hg&&a.Mk<c.length;){var e=hqa(a,c);
if(e==i6){4==b&&(a.dg=4,j6(15),d=!1);break}else if(e==k6){a.dg=4;j6(16);d=!1;break}else l6(a,e)}4==b&&0==c.length&&(a.dg=1,j6(17),d=!1);a.se=a.se&&d;d||(m6(a),n6(a))},hqa=function(a,b){var c=a.Mk,d=b.indexOf("\n",c);
if(-1==d)return i6;c=Number(b.substring(c,d));if(isNaN(c))return k6;d+=1;if(d+c>b.length)return i6;var e=b.substr(d,c);a.Mk=d+c;return e},r6=function(a,b){a.si=(0,g.D)();
h6(a);var c=b?window.location.hostname:"";a.wg=a.cg.clone();g.bn(a.wg,"DOMAIN",c);g.bn(a.wg,"t",a.A);try{a.we=new ActiveXObject("htmlfile")}catch(n){m6(a);a.dg=7;j6(22);n6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in p6)k=p6[l];else if(l in q6)k=p6[l]=q6[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
p6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Tc(g.qc("b/12014412"),d+"</body></html>");a.we.open();a.we.write(g.Nc(c));a.we.close();a.we.parentWindow.m=(0,g.y)(a.NK,a);a.we.parentWindow.d=(0,g.y)(a.Qy,a,!0);a.we.parentWindow.rpcClose=(0,g.y)(a.Qy,a,!1);c=a.we.createElement("DIV");a.we.parentWindow.document.body.appendChild(c);d=g.Cc(a.wg.toString());d=g.$c(g.zc(d));d=g.Tc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Uc(c,d);a.g.ne(1)},h6=function(a){a.Ws=(0,g.D)()+a.o;
s6(a,a.o)},s6=function(a,b){if(null!=a.Ki)throw Error("WatchDog timer not null");
a.Ki=t6((0,g.y)(a.XK,a),b)},u6=function(a){a.Ki&&(g.w.clearTimeout(a.Ki),a.Ki=null)},n6=function(a){a.g.Pv()||a.Hg||a.g.Ym(a)},m6=function(a){u6(a);
g.sf(a.pn);a.pn=null;a.i.stop();g.kn(a.ba);if(a.tc){var b=a.tc;a.tc=null;b.abort();b.dispose()}a.we&&(a.we=null)},l6=function(a,b){try{a.g.Ky(a,b),a.g.ne(4)}catch(c){}},w6=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;v6(a,b,function(k){k?c(!0):g.w.setTimeout(function(){w6(a,b,c,d,f)},f)})}},v6=function(a,b,c){var d=new Image;
d.onload=function(){try{x6(d),c(!0)}catch(e){}};
d.onerror=function(){try{x6(d),c(!1)}catch(e){}};
d.onabort=function(){try{x6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{x6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
w5(d,a)},x6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},y6=function(a){this.g=a;
this.i=new c6},A6=function(a){var b=z6(a.g,a.Wi,"/mail/images/cleardot.gif");
i5(b);w6(b.toString(),5E3,(0,g.y)(a.XB,a),3,2E3);a.ne(1)},C6=function(a){var b=a.g.F;
if(null!=b)j6(5),b?(j6(11),B6(a.g,a,!1)):(j6(12),B6(a.g,a,!0));else if(a.zd=new d6(a,void 0,void 0,void 0),a.zd.Rg=a.Np,b=a.g,b=z6(b,b.Dk()?a.Cj:null,a.Op),j6(5),!g.Od||g.rd(10))j5(b,"TYPE","xmlhttp"),g6(a.zd,b,!1,a.Cj,!1);else{j5(b,"TYPE","html");var c=a.zd;a=!!a.Cj;c.Ph=3;c.cg=i5(b.clone());r6(c,a)}},D6=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new c6;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},iqa=function(a,b){this.g=a;
this.map=b;this.context=null},E6=function(a){g.uf.call(this,"statevent",a)},F6=function(a,b){g.uf.call(this,"timingevent",a);
this.size=b},G6=function(a){g.uf.call(this,"serverreachability",a)},K6=function(a){H6(a);
if(3==a.g){var b=a.ik++,c=a.Ll.clone();g.bn(c,"SID",a.l);g.bn(c,"RID",b);g.bn(c,"TYPE","terminate");I6(a,c);b=new d6(a,a.l,b,void 0);b.Ph=2;b.cg=i5(c.clone());w5(new Image,b.cg.toString());b.si=(0,g.D)();h6(b)}J6(a)},M6=function(a){a.pC(1,0);
a.Ll=z6(a,null,a.Mp);L6(a)},H6=function(a){a.Tf&&(a.Tf.abort(),a.Tf=null);
a.Rb&&(a.Rb.cancel(),a.Rb=null);a.ff&&(g.w.clearTimeout(a.ff),a.ff=null);N6(a);a.ud&&(a.ud.cancel(),a.ud=null);a.Yf&&(g.w.clearTimeout(a.Yf),a.Yf=null)},O6=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new iqa(a.YG++,b));2!=a.g&&3!=a.g||L6(a)},L6=function(a){a.ud||a.Yf||(a.Yf=t6((0,g.y)(a.Py,a),0),a.Kh=0)},R6=function(a,b){if(1==a.g){if(!b){a.ik=Math.floor(1E5*Math.random());
var c=a.ik++,d=new d6(a,"",c,void 0);d.Rg=null;var e=P6(a),f=a.Ll.clone();g.bn(f,"RID",c);g.bn(f,"CVER","1");I6(a,f);f6(d,f,e);a.ud=d;a.g=2}}else 3==a.g&&(b?Q6(a,b):0==a.i.length||a.ud||Q6(a))},Q6=function(a,b){if(b)if(6<a.Ig){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.ik-1;var d=P6(a)}else c=b.B,d=b.mh;else c=a.ik++,d=P6(a);var e=a.Ll.clone();g.bn(e,"SID",a.l);g.bn(e,"RID",c);g.bn(e,"AID",a.Yh);I6(a,e);c=new d6(a,a.l,c,a.Kh+1);c.Rg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ud=c;f6(c,e,d)},I6=function(a,b){if(a.Sc){var c=a.Sc.vv();
c&&g.Jb(c,function(d,e){g.bn(b,e,d)})}},P6=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Ig&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Ig?e:f-d;try{g.Jb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},S6=function(a){a.Rb||a.ff||(a.B=1,a.ff=t6((0,g.y)(a.Oy,a),0),a.Eh=0)},U6=function(a){if(a.Rb||a.ff||3<=a.Eh)return!1;
a.B++;a.ff=t6((0,g.y)(a.Oy,a),T6(a,a.Eh));a.Eh++;return!0},B6=function(a,b,c){a.Wn=c;
a.Ee=b.tf;a.A||M6(a)},N6=function(a){null!=a.Mg&&(g.w.clearTimeout(a.Mg),a.Mg=null)},T6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},W6=function(a,b){if(2==b||9==b){var c=null;
a.Sc&&(c=null);var d=(0,g.y)(a.VL,a);c||(c=new g.Um("//www.google.com/images/cleardot.gif"),i5(c));v6(c.toString(),1E4,d)}else j6(2);V6(a,b)},V6=function(a,b){a.g=0;
a.Sc&&a.Sc.wu(b);J6(a);H6(a)},J6=function(a){a.g=0;
a.Ee=-1;if(a.Sc)if(0==a.o.length&&0==a.i.length)a.Sc.Yo();else{g.fb(a.o);var b=g.fb(a.i);a.o.length=0;a.i.length=0;a.Sc.Yo(b)}},z6=function(a,b,c){var d=g.cn(c);
if(""!=d.g)b&&g.Wm(d,b+"."+d.g),g.Xm(d,d.u);else{var e=window.location;d=Vpa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.jj&&g.Jb(a.jj,function(f,k){g.bn(d,k,f)});
g.bn(d,"VER",a.Ig);I6(a,d);return d},t6=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},j6=function(a){X6.dispatchEvent(new E6(X6,a))},Y6=function(){},jqa=function(a,b){this.action=a;
this.params=b||{}},Z6=function(a,b){g.H.call(this);
this.g=new g.N(this.FK,0,this);g.I(this,this.g);this.Uc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.y)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.y)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},$6=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Jo;this.i=new Z6(this.rM,this);this.g=null;this.Za=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.I=c||!1},kqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Wn,sessionId:a.g.l,arrayId:a.g.Yh}},a7=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&R6(a.g),K6(a.g));a.D=0},b7=function(a){return!!a.g&&3==a.g.g},lqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},c7=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=g.Xg(a)||"";b&&(this.port=":"+b);this.domain=g.Vg(a)||"";a=g.Hb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Gb(a,"10.0")&&(this.i=!1))},d7=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.fh(c+b,{})},e7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),md:g.Qa(a.u,e)};c&&(a.rb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Nq(b,a)},mqa=function(){var a=f7;
g7();h7.push(a);i7(h7)},j7=function(a,b){g7();
var c=h7,d=nqa(a,String(b));0==c.length?oqa(d):(i7(c),(0,g.B)(c,function(e){e(d)}))},g7=function(){h7||(h7=g.x("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",h7,void 0))},oqa=function(a){var b=(k7+1)%50;
k7=b;l7[b]=a;m7||(m7=49==b)},i7=function(a){var b=l7;
if(b[0]){var c=k7,d=m7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(f){f(e)})}while(d!=c);
l7=Array(50);k7=-1;m7=!1}},nqa=function(a,b){var c=((0,g.D)()-pqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},n7=function(a){g.P.call(this);
this.B=a;this.g=[]},o7=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},qqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.$d)(a.g,function(f){return!!I5(b,f)});
for(var d=0,e=b.length;d<e;d++)c=o7(a,b[d])||c;return c},rqa=function(a,b){var c=a.g.length;
a.g=(0,g.$d)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},p7=function(a,b,c,d){g.P.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.za=NaN},r7=function(a){n7.call(this,"LocalScreenService");
this.l=a;this.i=NaN;q7(this);this.info("Initializing with "+G5(this.g))},s7=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(d){return d.id}),c=d7(a.l,"/pairing/get_lounge_token_batch");
e7(a.l,c,{screen_ids:b.join(",")},(0,g.y)(a.WC,a),(0,g.y)(a.VC,a))}},q7=function(a){var b=E5(Q5());
b=(0,g.$d)(b,function(c){return!c.uuid});
return qqa(a,b)},t7=function(a,b){cqa((0,g.G)(a.g,D5));
b&&R5()},v7=function(a,b){g.P.call(this);
this.A=b;var c=g.nt("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Za(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;u7("Initialized with "+g.Ng(this.g))},w7=function(a,b,c){var d=d7(a.u,"/pairing/get_screen_availability");
e7(a.u,d,{lounge_token:b.token},(0,g.y)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.y)(function(){c(!1)},a))},x7=function(a,b){a:if(v5(b)!=v5(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(u7("Updated online screens: "+g.Ng(a.g)),a.g=b,a.N("screenChange"));sqa(a)},y7=function(a){isNaN(a.l)||g.Sp(a.l);
a.l=g.Qp((0,g.y)(a.Xr,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},u7=function(a){j7("OnlineScreenService",a)},z7=function(a){var b={};
(0,g.B)(a.A(),function(c){c.token?b[c.token]=c.id:this.Jb("Requesting availability of screen w/o lounge token.")});
return b},sqa=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.pb(a);a.length?g.mt("yt-remote-online-screen-ids",a.join(","),60):g.ot("yt-remote-online-screen-ids")},A7=function(a){n7.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};tqa(this)},C7=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Fd();if(k=(c?J5(k,c):null)||J5(k,b)){k.uuid=b;var l=B7(a,k);w7(a.i,l,function(m){e(m?l:null)})}else c?uqa(a,c,(0,g.y)(function(m){var n=B7(this,new B5({name:d,
screenId:c,loungeToken:m,dialId:b||""}));w7(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},D7=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},uqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={rb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Nq(d7(a.A,"/pairing/get_lounge_token_batch"),e)},E7=function(a){a.g=a.l.Fd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+G5(a.g))},tqa=function(a){F7(a);
a.l=new r7(a.A);a.l.subscribe("screenChange",(0,g.y)(a.fD,a));E7(a);a.o=E5(g.nt("yt-remote-automatic-screen-cache")||[]);F7(a);a.info("Initializing automatic screens: "+G5(a.o));a.i=new v7(a.A,(0,g.y)(a.Fd,a,!0));a.i.subscribe("screenChange",(0,g.y)(function(){this.N("onlineScreenChange")},a))},B7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=J5(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.mt("yt-remote-automatic-screen-cache",(0,g.G)(a.o,D5)));F7(a);a.u[b.uuid]=b.id;g.mt("yt-remote-device-id-map",a.u,31536E3);return b},F7=function(a){a.u=g.nt("yt-remote-device-id-map")||{}},G7=function(a,b,c){g.P.call(this);
this.P=c;this.F=a;this.i=b;this.l=null},H7=function(a,b){j7(a.P,b)},J7=function(a,b){G7.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.y)(this.xM,this);this.u=(0,g.y)(this.iL,this);this.o=g.Qp((0,g.y)(function(){I7(this,null)},this),12E4)},vqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Ng(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.y)(function(){H7(this,"Failed to send message: getMdxSessionStatus.")},a)):H7(a,"Sending yt message without session: "+g.Ng(b))},I7=function(a,b){g.Sp(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.y)(a.Zm,a),d=(0,g.y)(a.Id,a);a.Iv(b,c,d,5)}}else a.Id(Error("Waiting for session status timed out."))},K7=function(a,b,c){G7.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.B=g.Ha;this.A=NaN;this.I=(0,g.y)(this.AM,this);this.g=g.Ha},L7=function(a){a.g=a.F.VA(a.H,a.i.label,a.i.friendlyName,(0,g.y)(function(b){this.g=g.Ha;
this.Zm(b)},a),(0,g.y)(function(b){this.g=g.Ha;
this.Id(b)},a))},M7=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}U5()&&(b.env_useStageMdx=1);return g.dh(b)},N7=function(a,b){G7.call(this,a,b,"ManualSession");
this.g=g.Qp((0,g.y)(this.ai,this,null),150)},O7=function(a,b,c,d){g.P.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.y)(this.OJ,this)},P7=function(a,b){return b?g.Wa(a.l,function(c){return C5(b,c.label)},a):null},Q7=function(a){j7("Controller",a)},f7=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},R7=function(a){return a.u||!!a.l.length||!!a.g},S7=function(a,b,c){b!=a.g&&(g.sf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.y)(a.Ny,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.ai(null)):a.N("yt-remote-cast2-session-change",null))},T7=function(a){var b=a.i.UA(),c=a.g&&a.g.i;
a=(0,g.G)(b,function(d){c&&C5(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=P7(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},zqa=function(a,b,c,d,e,f,k){wqa()?xqa(b,e,f,k)&&(V7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?W7(a,c):(window.__onGCastApiAvailable=function(l,m){l?W7(a,c):(X7("Failed to load cast API: "+m),Y7(!1),V7(!1),g.ot("yt-remote-cast-available"),g.ot("yt-remote-cast-receiver"),Z7(),c(!1))},d?g.cq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?gqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?Z5():(a6(),Y5(yqa.map(eqa))))):U7("Cannot initialize because not running Chrome")},Z7=function(){U7("dispose");
var a=$7();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);a8(!1);g.Yp(b8);b8.length=0},c8=function(){return!!g.nt("yt-remote-cast-installed")},d8=function(){var a=g.nt("yt-remote-cast-receiver");
return a?a.friendlyName:null},e8=function(){U7("clearCurrentReceiver");
g.ot("yt-remote-cast-receiver")},f8=function(){return c8()?$7()?$7().getCastSession():(X7("getCastSelector: Cast is not initialized."),null):(X7("getCastSelector: Cast API is not installed!"),null)},h8=function(){c8()?$7()?g8()?(U7("Requesting cast selector."),$7().requestSession()):(U7("Wait for cast API to be ready to request the session."),b8.push(g.Xp("yt-remote-cast2-api-ready",h8))):X7("requestCastSelector: Cast is not initialized."):X7("requestCastSelector: Cast API is not installed!")},i8=
function(a,b){g8()?$7().setConnectedScreenStatus(a,b):X7("setConnectedScreenStatus called before ready.")},wqa=function(){var a=0<=g.Hb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Xw||a},Aqa=function(a,b){$7().init(a,b)},xqa=function(a,b,c,d){var e=!1;
$7()||(a=new O7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.mt("yt-remote-cast-available",f);z5("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){U7("onReceiverSelected: "+f.friendlyName);
g.mt("yt-remote-cast-receiver",f);z5("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){U7("onReceiverResumed: "+f.friendlyName);
g.mt("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){U7("onSessionChange: "+F5(f));
f||g.ot("yt-remote-cast-receiver");z5("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
U7("cloudview.createSingleton_: "+e);return e},$7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},W7=function(a,b){Y7(!0);
V7(!1);Aqa(a,function(c){c?(a8(!0),g.$p("yt-remote-cast2-api-ready")):(X7("Failed to initialize cast API."),Y7(!1),g.ot("yt-remote-cast-available"),g.ot("yt-remote-cast-receiver"),Z7());b(c)})},U7=function(a){j7("cloudview",a)},X7=function(a){j7("cloudview",a)},Y7=function(a){U7("setCastInstalled_ "+a);
g.mt("yt-remote-cast-installed",a)},g8=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},a8=function(a){U7("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},V7=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},j8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Ge=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},k8=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Ge=!1;a.hasNext=!1;a.B=0;a.A=(0,g.D)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},l8=function(a){return 1==a.playerState?((0,g.D)()-a.A)/1E3:0},m8=function(a,b){a.B=b;
a.A=(0,g.D)()},n8=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},o8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&k8(a)},p8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.Ge;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},s8=function(a,b){g.P.call(this);
this.g=0;this.o=a;this.A=[];this.u=new y5;this.l=this.i=null;this.F=(0,g.y)(this.IH,this);this.B=(0,g.y)(this.kk,this);this.D=(0,g.y)(this.HH,this);this.H=(0,g.y)(this.UH,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Zs,this),q8(this))):c=3;0!=c&&(b?this.Zs(c):g.Qp((0,g.y)(function(){this.Zs(c)},this),0));
var d=f8();d&&r8(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},t8=function(a){return new j8(a.o.getPlayerContextData())},q8=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Qa(this.LJ,b),this))},a)},u8=function(a){(0,g.B)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},v8=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},x8=function(a,b,c){var d=t8(a);
m8(d,c);-1E3!=d.playerState&&(d.playerState=b);w8(a,d)},y8=function(a,b,c){a.o.sendMessage(b,c)},w8=function(a,b){u8(a);
a.o.setPlayerContextData(p8(b));q8(a)},r8=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.kk(null));
a.l=b;a.l&&(j7("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.kk(a.l.media[0]))},z8=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=t8(a);b.contentId!=d.videoId&&j7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;m8(d,a.i.getEstimatedTime());w8(a,d)}else j7("CP","No cast media video. Ignoring state update.")},A8=function(a,b,c){return(0,g.y)(function(d){this.Jb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Jb("Retrying "+b+" using MDx browser channel."),y8(this,b,c))},a)},B8=function(a,b,c){g.P.call(this);
this.u=NaN;this.M=!1;this.H=this.F=this.I=this.P=NaN;this.O=[];this.o=this.B=this.l=this.Qa=this.g=null;this.na=a;this.O.push(g.Pr(window,"beforeunload",(0,g.y)(this.PC,this)));this.i=[];this.Qa=new j8;this.V=b.id;this.g=Bqa(this,c);this.g.subscribe("handlerOpened",this.MH,this);this.g.subscribe("handlerClosed",this.JH,this);this.g.subscribe("handlerError",this.KH,this);this.g.subscribe("handlerMessage",this.LH,this);lqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Qa.videoId;
g.pt()&&g.mt("yt-remote-session-video-id",d)},this)},C8=function(a){j7("conn",a)},Bqa=function(a,b){return new $6(d7(a.na,"/bc"),b)},D8=function(a,b){a.N("proxyStateChange",b)},Cqa=function(a){a.u=g.Qp((0,g.y)(function(){C8("Connecting timeout");
this.A(1)},a),2E4)},E8=function(a){g.Sp(a.u);
a.u=NaN},F8=function(a){g.Sp(a.P);
a.P=NaN},Dqa=function(a){G8(a);
a.I=g.Qp((0,g.y)(function(){H8(this,"getNowPlaying")},a),2E4)},G8=function(a){g.Sp(a.I);
a.I=NaN},Eqa=function(a,b){b&&(E8(a),F8(a));
b==(b7(a.g)&&isNaN(a.u))?b&&(D8(a,1),H8(a,"getSubtitlesTrack")):b?(a.R()&&a.Qa.reset(),D8(a,1),H8(a,"getNowPlaying"),I8(a)):a.A(1)},Fqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Qa.videoId&&(g.Xb(b.params)?a.Qa.g=null:a.Qa.g=b.params,a.N("remotePlayerChange"))},Gqa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Qa.listId=b.params.listId||a.Qa.listId;o8(a.Qa,c,d);a.N("remoteQueueChange")},Iqa=function(a,b){b.params=b.params||{};
Gqa(a,b);Hqa(a,b);a.N("autoplayDismissed")},Hqa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
m8(a.Qa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Qa.playerState&&(c=-1E3);a.Qa.playerState=c;c=Number(b.params.loadedTime);a.Qa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Qa.D=isNaN(c)?0:c;c=a.Qa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Qa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Qa.playerState?Dqa(a):G8(a);a.N("remotePlayerChange")},Jqa=function(a,b){if(-1E3!=
a.Qa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Qa.playerState=c;c=parseInt(b.params.currentTime,10);m8(a.Qa,isNaN(c)?0:c);a.N("remotePlayerChange")}},Kqa=function(a,b){var c="true"==b.params.muted;
a.Qa.volume=parseInt(b.params.volume,10);a.Qa.muted=c;a.N("remotePlayerChange")},Lqa=function(a,b){a.B=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},Mqa=function(a,b){var c="true"==b.params.hasNext;
a.Qa.Ge="true"==b.params.hasPrevious;a.Qa.hasNext=c;a.N("previousNextChange")},I8=function(a){g.Sp(a.H);
a.H=g.Qp((0,g.y)(a.A,a,1),864E5)},H8=function(a,b,c){c?C8("Sending: action="+b+", params="+g.Ng(c)):C8("Sending: action="+b);
a.g.sendMessage(b,c)},J8=function(a){n7.call(this,"ScreenServiceProxy");
this.Gc=a;this.i=[];this.i.push(this.Gc.$_s("screenChange",(0,g.y)(this.vM,this)));this.i.push(this.Gc.$_s("onlineScreenChange",(0,g.y)(this.pJ,this)))},Rqa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Ip("MDX_CONFIG")||b;aqa();O5();K8||(K8=new c7(b?b.loungeApiHost:void 0),U5()&&(K8.g="/api/loungedev"));L8||(L8=g.x("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",L8,void 0));Nqa();var c=M8();if(!c){var d=new A7(K8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=M8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);zqa(a,d,function(m){m?N8()&&i8(N8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){z5("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),O8("Initializing: "+g.Ng(b)),P8.push(g.Xp("yt-remote-cast2-availability-change",function(){z5("yt-remote-receiver-availability-change")})),P8.push(g.Xp("yt-remote-cast2-receiver-selected",function(){Q8(null);
z5("yt-remote-auto-connect","cast-selector-receiver")})),P8.push(g.Xp("yt-remote-cast2-receiver-resumed",function(){z5("yt-remote-receiver-resumed","cast-selector-receiver")})),P8.push(g.Xp("yt-remote-cast2-session-change",Oqa)),P8.push(g.Xp("yt-remote-connection-change",function(m){m?i8(N8(),"YouTube TV"):R8()||(i8(null,null),e8())})),a=S8(),b.isAuto&&(a.id+="#dial"),g.Eq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),O8(" -- with channel params: "+
g.Ng(a)),Pqa(a),c.start(),N8()||Qqa())},Tqa=function(){var a=Sqa();
c8()&&g.nt("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Sqa=function(){var a=M8().Gc.$_gos();
var b=T8();b&&U8()&&(I5(a,b)||a.push(b));return $pa(a)},V8=function(){var a=Uqa();
!a&&c8()&&d8()&&(a={key:"cast-selector-receiver",name:d8()});return a},Uqa=function(){var a=Sqa(),b=T8();
b||(b=R8());return g.Wa(a,function(c){return b&&C5(b,c.key)?!0:!1})},T8=function(){var a=N8();
if(!a)return null;var b=M8().Fd();return J5(b,a)},Oqa=function(a){O8("remote.onCastSessionChange_: "+F5(a));
if(a){var b=T8();b&&b.id==a.id?i8(b.id,"YouTube TV"):(b&&W8(),X8(a,1))}else U8()&&W8()},W8=function(){g8()?$7().stopSession():X7("stopSession called before API ready.");
var a=U8();a&&(a.disconnect(1),Y8(null))},Z8=function(){var a=U8();
return!!a&&3!=a.getProxyState()},O8=function(a){j7("remote",a)},M8=function(){if(!$8){var a=g.x("yt.mdx.remote.screenService_");
$8=a?new J8(a):null}return $8},N8=function(){return g.x("yt.mdx.remote.currentScreenId_")},Vqa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},Wqa=function(){return g.x("yt.mdx.remote.connectData_")},Q8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},U8=function(){return g.x("yt.mdx.remote.connection_")},Y8=function(a){var b=U8();
Q8(null);a||Vqa("");g.Ga("yt.mdx.remote.connection_",a,void 0);L8&&((0,g.B)(L8,function(c){c(a)}),L8.length=0);
b&&!a?z5("yt-remote-connection-change",!1):!b&&a&&z5("yt-remote-connection-change",!0)},R8=function(){var a=g.pt();
if(!a)return null;var b=M8().Fd();return J5(b,a)},X8=function(a,b){T8()&&T8();
Vqa(a.id);var c=new B8(K8,a,S8());c.connect(b,Wqa());c.subscribe("beforeDisconnect",function(d){z5("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){U8()&&Y8(null)});
Y8(c)},Qqa=function(){var a=R8();
a?(O8("Resume connection to: "+F5(a)),X8(a,0)):(S5(),e8(),O8("Skipping connecting because no session screen found."))},Nqa=function(){var a=S8();
if(g.Xb(a)){a=N5();var b=g.nt("yt-remote-session-name")||"",c=g.nt("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},S8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},Pqa=function(a){a?(g.mt("yt-remote-session-app",a.app),g.mt("yt-remote-session-name",a.name)):(g.ot("yt-remote-session-app"),g.ot("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},a9=function(a,b,c){g.H.call(this);
this.u=a;this.i=b;this.l=new g.bs(this);g.I(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.GI);this.l.K(b,"captionschanged",this.GH);this.l.K(b,"captionssettingschanged",this.iA);this.l.K(b,"videoplayerreset",this.an);this.l.K(b,"mdxautoplaycancel",this.WB);this.O=this.l.K(b,"onVolumeChange",this.yy);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.Jy,this);c.subscribe("remotePlayerChange",this.mk,this);c.subscribe("remoteQueueChange",this.an,this);c.subscribe("autoplayUpNext",this.ky,
this);c.subscribe("previousNextChange",this.Gy,this);c.subscribe("nowAutoplaying",this.Cy,this);c.subscribe("autoplayDismissed",this.jy,this);this.suggestion=null;this.F=new g.$C(64);this.o=new g.N(this.gA,500,this);g.I(this,this.o);this.A=new g.N(this.hA,1E3,this);g.I(this,this.A);this.I=new b6(this.eM,0,this);g.I(this,this.I);this.B={};this.P=new g.N(this.HA,1E3,this);g.I(this,this.P);this.H=new g.Cl(this.mF,1E3,this);g.I(this,this.H);this.M=g.Ha;this.iA();this.an();this.mk()},b9=function(a,b){a.u.nd(b,
a.i.getVideoData().lengthSeconds)},Xqa=function(a){b9(a,0);
a.o.stop();c9(a,new g.$C(64))},e9=function(a,b){if(d9(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.Wz(a.i.getVideoData(1).videoId,c);a.B=t8(a.g).g}},f9=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Sa;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.vf,u5(c));c9(a,new g.$C(1))},Yqa=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{QP:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},d9=function(a){return t8(a.g).videoId==a.i.getVideoData(1).videoId},c9=function(a,b){a.A.stop();
var c=a.F;if(!g.fD(c,b)){var d=g.V(b,2);d!=g.V(a.F,2)&&g.eK(a.i,d);a.F=b;Zqa(a.u,c,b)}},g9=function(a){g.U.call(this,{C:"div",
G:"ytp-remote",J:[{C:"div",G:"ytp-remote-display-status",J:[{C:"div",G:"ytp-remote-display-status-icon",J:[g.qP()]},{C:"div",G:"ytp-remote-display-status-text",U:"{{statustext}}"}]}]});this.l=new g.aQ(this,250);g.I(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);$qa(this,g.aK(a))},$qa=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.V(b,128)?g.pN("Error on $RECEIVER_NAME",c):g.gD(b)||g.V(b,4)?g.pN("Playing on $RECEIVER_NAME",c):g.pN("Connected to $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},h9=function(a,b){g.IT.call(this,"Play on",0,a,b);
this.l=a;this.F={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},i9=function(a){g.FK.call(this,a);
this.i={key:H5(),name:"This computer"};this.o=null;this.u=[];this.B=this.g=null;this.A=[this.i];this.l=this.i;this.Xj=new g.$C(64);this.D=0;this.pm=-1;if(!g.dz(g.W(this.player))){a=this.player;var b=g.yC(a);b&&(b=b.Km())&&(b=new h9(a,b),g.I(this,b));b=new g9(a);g.I(this,b);g.rK(a,b.element,4)}},Zqa=function(a,b,c){a.Xj=c;
a.player.N("presentingplayerstatechange",new g.kD(c,b))},j9=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)W8();
else{a.l=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.oa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.vf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(d=u5(d))&&(c.locationInfo=d);d=c}else d=null;O8("Connecting to: "+g.Ng(b));"cast-selector-receiver"==b.key?
(Q8(d||null),g8()?$7().setLaunchParams(d||null):X7("setLaunchParams called before ready.")):!d&&Z8()&&N8()==b.key?z5("yt-remote-connection-change",!0):(W8(),Q8(d||null),d=M8().Fd(),(d=J5(d,b.key))&&X8(d,1))}},Ppa=/^https?$/i,ara=["POST",
"PUT"];g.A(s5,g.Uf);g.h=s5.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.F+"; newUri="+a);b=b?b.toUpperCase():"GET";this.F=a;this.l="";this.u=0;this.aa=b;this.O=!1;this.i=!0;this.g=this.M?k5(this.M):k5(g.JY);this.P=this.M?this.M.getOptions():g.JY.getOptions();this.g.onreadystatechange=(0,g.y)(this.Rv,this);try{h5(l5(this,"Opening Xhr")),this.V=!0,this.g.open(b,String(a),!0),this.V=!1}catch(f){h5(l5(this,"Error opening Xhr: "+f.message));p5(this,f);return}a=c||
"";var e=this.headers.clone();d&&Mpa(d,function(f,k){e.set(k,f)});
d=g.Wa(e.Dd(),Npa);c=g.w.FormData&&a instanceof g.w.FormData;!g.Za(ara,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.Y&&(this.g.responseType=this.Y);"withCredentials"in this.g&&this.g.withCredentials!==this.R&&(this.g.withCredentials=this.R);try{m5(this),0<this.A&&(this.I=Opa(this.g),h5(l5(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.y)(this.Sv,this)):this.B=g.Jg(this.Sv,this.A,this)),h5(l5(this,"Sending request")),this.D=!0,this.g.send(a),this.D=!1}catch(f){h5(l5(this,"Send error: "+f.message)),p5(this,f)}};
g.h.Sv=function(){"undefined"!=typeof g.nY&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,l5(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(l5(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),o5(this))};
g.h.T=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),o5(this,!0));s5.Ha.T.call(this)};
g.h.Rv=function(){this.ea()||(this.V||this.D||this.o?r5(this):this.NJ())};
g.h.NJ=function(){r5(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<q5(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.v(this.l)?this.l:String(this.l)};
var q6={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},p6={"'":"\\'"},bra={};g.h=y5.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.Za(this.g,a)||g.Za(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.yma)(b,a);0<=c?(g.ab(b,c),b=!0):b=!1;return b||g.bb(this.i,a)};
g.h.yc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var Ypa={UM:"atp",eP:"ska",TO:"que",tO:"mus",dP:"sus",KN:"dsp",aP:"seq"};A5.prototype.Uf=function(){var a=new A5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var T5,M5="",$5=V5("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",fqa=V5("loadCastFramework")||V5("loadCastApplicationFramework"),yqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(b6,g.H);g.h=b6.prototype;g.h.LC=function(a){this.o=arguments;this.g=!1;this.za?this.l=(0,g.D)()+this.Uc:this.za=g.Jg(this.u,this.Uc)};
g.h.stop=function(){this.za&&(g.w.clearTimeout(this.za),this.za=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.T=function(){this.stop();b6.Ha.T.call(this)};
g.h.MC=function(){this.l?(this.za=g.Jg(this.u,this.l-(0,g.D)()),this.l=null):(this.za=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};c6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
c6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=d6.prototype;g.h.Rg=null;g.h.se=!1;g.h.Ki=null;g.h.Ws=null;g.h.si=null;g.h.Ph=null;g.h.cg=null;g.h.wg=null;g.h.mh=null;g.h.tc=null;g.h.Mk=0;g.h.we=null;g.h.Yn=null;g.h.dg=null;g.h.Dj=-1;g.h.Iz=!0;g.h.Hg=!1;g.h.Pp=0;g.h.pn=null;var k6={},i6={};g.h=d6.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.sL=function(a){a=a.target;var b=this.pn;b&&3==q5(a)?b.zj():this.QA(a)};
g.h.QA=function(a){try{if(a==this.tc)a:{var b=q5(this.tc),c=this.tc.u,d=this.tc.getStatus();if(g.Od&&!g.rd(10)||g.Qd&&!g.qd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Fh&&!t5(this.tc))break a;this.Hg||4!=b||7==c||(8==c||0>=d?this.g.ne(3):this.g.ne(2));u6(this);var e=this.tc.getStatus();this.Dj=e;var f=t5(this.tc);(this.se=200==e)?(4==b&&m6(this),this.u?(o6(this,b,f),g.Fh&&this.se&&3==b&&(this.ba.da(this.i,"tick",this.oL),this.i.start())):l6(this,f),this.se&&!this.Hg&&(4==b?this.g.Ym(this):(this.se=
!1,h6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.dg=3,j6(13)):(this.dg=0,j6(14)),m6(this),n6(this))}}catch(k){this.tc&&t5(this.tc)}finally{}};
g.h.oL=function(){var a=q5(this.tc),b=t5(this.tc);this.Mk<b.length&&(u6(this),o6(this,a,b),this.se&&4!=a&&h6(this))};
g.h.NK=function(a){t6((0,g.y)(this.MK,this,a),0)};
g.h.MK=function(a){this.Hg||(u6(this),l6(this,a),h6(this))};
g.h.Qy=function(a){t6((0,g.y)(this.LK,this,a),0)};
g.h.LK=function(a){this.Hg||(m6(this),this.se=a,this.g.Ym(this),this.g.ne(4))};
g.h.cancel=function(){this.Hg=!0;m6(this)};
g.h.XK=function(){this.Ki=null;var a=(0,g.D)();0<=a-this.Ws?(2!=this.Ph&&this.g.ne(3),m6(this),this.dg=2,j6(18),n6(this)):s6(this,this.Ws-a)};
g.h.getLastError=function(){return this.dg};g.h=y6.prototype;g.h.Np=null;g.h.zd=null;g.h.qn=!1;g.h.Qv=null;g.h.Jl=null;g.h.Eq=null;g.h.Op=null;g.h.Wd=null;g.h.tf=-1;g.h.Cj=null;g.h.Wi=null;g.h.connect=function(a){this.Op=a;a=z6(this.g,null,this.Op);j6(3);this.Qv=(0,g.D)();var b=this.g.D;null!=b?(this.Cj=b[0],(this.Wi=b[1])?(this.Wd=1,A6(this)):(this.Wd=2,C6(this))):(j5(a,"MODE","init"),this.zd=new d6(this,void 0,void 0,void 0),this.zd.Rg=this.Np,g6(this.zd,a,!1,null,!0),this.Wd=0)};
g.h.XB=function(a){if(a)this.Wd=2,C6(this);else{j6(4);var b=this.g;b.Ee=b.Tf.tf;W6(b,9)}a&&this.ne(2)};
g.h.kp=function(a){return this.g.kp(a)};
g.h.abort=function(){this.zd&&(this.zd.cancel(),this.zd=null);this.tf=-1};
g.h.Pv=function(){return!1};
g.h.Ky=function(a,b){this.tf=a.Dj;if(0==this.Wd)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ee=this.tf;W6(c,2);return}this.Cj=c[0];this.Wi=c[1]}else c=this.g,c.Ee=this.tf,W6(c,2);else if(2==this.Wd)if(this.qn)j6(7),this.Eq=(0,g.D)();else if("11111"==b){if(j6(6),this.qn=!0,this.Jl=(0,g.D)(),c=this.Jl-this.Qv,!g.Od||g.rd(10)||500>c)this.tf=200,this.zd.cancel(),j6(12),B6(this.g,this,!0)}else j6(8),this.Jl=this.Eq=(0,g.D)(),this.qn=!1};
g.h.Ym=function(){this.tf=this.zd.Dj;if(this.zd.se)0==this.Wd?this.Wi?(this.Wd=1,A6(this)):(this.Wd=2,C6(this)):2==this.Wd&&((!g.Od||g.rd(10)?!this.qn:200>this.Eq-this.Jl)?(j6(11),B6(this.g,this,!1)):(j6(12),B6(this.g,this,!0)));else{0==this.Wd?j6(9):2==this.Wd&&j6(10);var a=this.g;this.zd.getLastError();a.Ee=this.tf;W6(a,2)}};
g.h.Dk=function(){return this.g.Dk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.ne=function(a){this.g.ne(a)};g.h=D6.prototype;g.h.jj=null;g.h.ud=null;g.h.Rb=null;g.h.Mp=null;g.h.Ll=null;g.h.nu=null;g.h.Ul=null;g.h.ik=0;g.h.YG=0;g.h.Sc=null;g.h.Yf=null;g.h.ff=null;g.h.Mg=null;g.h.Tf=null;g.h.Wn=null;g.h.Yh=-1;g.h.xw=-1;g.h.Ee=-1;g.h.Kh=0;g.h.Eh=0;g.h.Ig=8;var X6=new g.Uf;g.A(E6,g.uf);g.A(F6,g.uf);g.A(G6,g.uf);g.h=D6.prototype;g.h.connect=function(a,b,c,d,e){j6(0);this.Mp=b;this.jj=c||{};d&&g.Ca(e)&&(this.jj.OSID=d,this.jj.OAID=e);this.A?(t6((0,g.y)(this.Eu,this,a),100),M6(this)):this.Eu(a)};
g.h.Eu=function(a){this.Tf=new y6(this);this.Tf.Np=null;this.Tf.i=this.u;this.Tf.connect(a)};
g.h.Pv=function(){return 0==this.g};
g.h.Py=function(a){this.Yf=null;R6(this,a)};
g.h.Oy=function(){this.ff=null;this.Rb=new d6(this,this.l,"rpc",this.B);this.Rb.Rg=null;this.Rb.Pp=0;var a=this.nu.clone();g.bn(a,"RID","rpc");g.bn(a,"SID",this.l);g.bn(a,"CI",this.Wn?"0":"1");g.bn(a,"AID",this.Yh);I6(this,a);if(!g.Od||g.rd(10))g.bn(a,"TYPE","xmlhttp"),g6(this.Rb,a,!0,this.Ul,!1);else{g.bn(a,"TYPE","html");var b=this.Rb,c=!!this.Ul;b.Ph=3;b.cg=i5(a.clone());r6(b,c)}};
g.h.Ky=function(a,b){if(0!=this.g&&(this.Rb==a||this.ud==a))if(this.Ee=a.Dj,this.ud==a&&3==this.g)if(7<this.Ig){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.ff){if(this.Rb)if(this.Rb.si+3E3<this.ud.si)N6(this),this.Rb.cancel(),this.Rb=null;else break a;U6(this);j6(19)}}else this.xw=c[1],0<this.xw-this.Yh&&37500>c[2]&&this.Wn&&0==this.Eh&&!this.Mg&&(this.Mg=t6((0,g.y)(this.CH,this),6E3));else W6(this,11)}else b!=bra.pN.g&&W6(this,11);else if(this.Rb==a&&
N6(this),!g.vb(b)){c=this.u.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.Yh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Ul=e[2],e=e[3],null!=e?this.Ig=e:this.Ig=6,this.g=3,this.Sc&&this.Sc.yu(),this.nu=z6(this,this.Dk()?this.Ul:null,this.Mp),S6(this)):"stop"==e[0]&&W6(this,7):3==this.g&&("stop"==e[0]?W6(this,7):"noop"!=e[0]&&this.Sc&&this.Sc.xu(e),this.Eh=0)}}};
g.h.CH=function(){null!=this.Mg&&(this.Mg=null,this.Rb.cancel(),this.Rb=null,U6(this),j6(20))};
g.h.Ym=function(a){if(this.Rb==a){N6(this);this.Rb=null;var b=2}else if(this.ud==a)this.ud=null,b=1;else return;this.Ee=a.Dj;if(0!=this.g)if(a.se)1==b?(b=(0,g.D)()-a.si,X6.dispatchEvent(new F6(X6,a.mh?a.mh.length:0,b,this.Kh)),L6(this),this.o.length=0):S6(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ee)){if(d=1==b)this.ud||this.Yf||1==this.g||2<=this.Kh?d=!1:(this.Yf=t6((0,g.y)(this.Py,this,a),T6(this,this.Kh)),this.Kh++,d=!0);d=!(d||2==b&&U6(this))}if(d)switch(c){case 1:W6(this,
5);break;case 4:W6(this,10);break;case 3:W6(this,6);break;case 7:W6(this,12);break;default:W6(this,2)}}};
g.h.pC=function(a){if(!g.Za(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.VL=function(a){a?j6(2):(j6(1),V6(this,8))};
g.h.kp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new s5;a.R=!1;return a};
g.h.isActive=function(){return!!this.Sc&&this.Sc.isActive(this)};
g.h.ne=function(a){X6.dispatchEvent(new G6(X6,a))};
g.h.Dk=function(){return!(!g.Od||g.rd(10))};
g.h=Y6.prototype;g.h.yu=function(){};
g.h.xu=function(){};
g.h.wu=function(){};
g.h.Yo=function(){};
g.h.vv=function(){return{}};
g.h.isActive=function(){return!0};g.A(Z6,g.H);g.h=Z6.prototype;g.h.FK=function(){this.Uc=Math.min(3E5,2*this.Uc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Uc+15E3*Math.random();g.oo(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Uc=5E3};g.A($6,Y6);g.h=$6.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Bf=function(a){return this.l.Sg(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.Za||(this.Za=!0,g.sf(this.l),a7(this),g.sf(this.i),this.i=null)};
g.h.ea=function(){return this.Za};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new D6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Sc=null);d.Sc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.Yh):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):b7(this)&&O6(this.g,c)};
g.h.yu=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)O6(this.g,a[b])}this.N("handlerOpened")};
g.h.wu=function(a){var b=2==a&&401==this.g.Ee;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Yo=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.vv=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.ec(a,this.u);return a};
g.h.xu=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),K6(this.g)):this.N("handlerMessage",new jqa(a[0],a[1]))};
g.h.rM=function(){this.i.isActive();var a=this.g,b=0;a.Rb&&b++;a.ud&&b++;0!=b||this.connect(this.u,this.o)};c7.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
c7.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
c7.prototype.u=function(a){a(Error("request timed out"))};var pqa=(0,g.D)(),h7=null,l7=Array(50),k7=-1,m7=!1;g.A(n7,g.P);n7.prototype.Fd=function(){return this.g};
n7.prototype.contains=function(a){return!!I5(this.g,a)};
n7.prototype.get=function(a){return a?J5(this.g,a):null};
n7.prototype.info=function(a){j7(this.B,a)};g.A(p7,g.P);var cra=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=p7.prototype;g.h.start=function(){!this.g&&isNaN(this.za)&&this.TA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.za)||(g.Sp(this.za),this.za=NaN)};
g.h.T=function(){this.stop();p7.Ha.T.call(this)};
g.h.TA=function(){this.za=NaN;this.g=g.Nq(d7(this.A,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.y)(this.tM,this),onError:(0,g.y)(this.sM,this),md:(0,g.y)(this.uM,this)})};
g.h.tM=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new B5(c))};
g.h.sM=function(a){this.g=null;a.status&&404==a.status?this.i>=cra.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=cra[this.i],this.za=g.Qp((0,g.y)(this.TA,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.uM=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};g.A(r7,n7);g.h=r7.prototype;g.h.start=function(){q7(this)&&this.N("screenChange");!g.nt("yt-remote-lounge-token-expiration")&&s7(this);g.Sp(this.i);this.i=g.Qp((0,g.y)(this.start,this),1E4)};
g.h.add=function(a,b){q7(this);o7(this,a);t7(this,!1);this.N("screenChange");b(a);a.token||s7(this)};
g.h.remove=function(a,b){var c=q7(this);rqa(this,a)&&(t7(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Sn=function(a,b,c,d){var e=q7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,t7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.T=function(){g.Sp(this.i);r7.Ha.T.call(this)};
g.h.WC=function(a){q7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}t7(this,!b);b&&j7(this.B,"Missed "+b+" lounge tokens.")};
g.h.VC=function(a){j7(this.B,"Requesting lounge tokens failed: "+a)};g.A(v7,g.P);g.h=v7.prototype;g.h.start=function(){var a=parseInt(g.nt("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?y7(this):(this.o=(0,g.D)()+3E5,g.mt("yt-remote-fast-check-period",this.o),this.Xr())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){u7("Updating availability on schedule.");var a=this.A(),b=g.Lb(this.g,function(c,d){return c&&!!J5(a,d)},this);
x7(this,b)};
g.h.T=function(){g.Sp(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);v7.Ha.T.call(this)};
g.h.Xr=function(){g.Sp(this.l);this.l=NaN;this.i&&this.i.abort();var a=z7(this);if(v5(a)){var b=d7(this.u,"/pairing/get_screen_availability");this.i=e7(this.u,b,{lounge_token:g.Rb(a).join(",")},(0,g.y)(this.jK,this,a),(0,g.y)(this.iK,this))}else x7(this,{}),y7(this)};
g.h.jK=function(a,b){this.i=null;var c=g.Rb(z7(this));if(g.qb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;x7(this,d);y7(this)}else this.Jb("Changing Screen set during request."),this.Xr()};
g.h.iK=function(a){this.Jb("Screen availability failed: "+a);this.i=null;y7(this)};
g.h.Jb=function(a){j7("OnlineScreenService",a)};g.A(A7,n7);g.h=A7.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Sn=function(a,b,c,d){this.l.contains(a)?this.l.Sn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,j7(this.B,a),d(Error(a)))};
g.h.Fd=function(a){return a?this.g:g.eb(this.g,(0,g.$d)(this.o,function(b){return!this.contains(b)},this))};
g.h.UA=function(){return(0,g.$d)(this.Fd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.VA=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new p7(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.y)(function(k){g.sf(f);d(B7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.sf(f);e(k)});
f.start();return(0,g.y)(f.stop,f)};
g.h.wM=function(a,b,c,d){g.Nq(d7(this.A,"/pairing/get_screen"),{method:"POST",rb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.y)(function(e,f){var k=new B5(f.screen||{});if(!k.name||D7(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);D7(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(B7(this,k))},this),
onError:(0,g.y)(function(e){d(Error("pairing request failed: "+e.status))},this),
md:(0,g.y)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.sf(this.l);g.sf(this.i);A7.Ha.T.call(this)};
g.h.fD=function(){E7(this);this.N("screenChange");this.i.update()};
A7.prototype.dispose=A7.prototype.dispose;g.A(G7,g.P);g.h=G7.prototype;g.h.Zm=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Id=function(a){this.ea()||(a&&H7(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){j7(this.P,a)};
g.h.XA=function(){return null};
g.h.qs=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.y)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.y)(function(){H7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.qs("");G7.Ha.T.call(this)};g.A(J7,G7);g.h=J7.prototype;g.h.os=function(a){if(this.g){if(this.g==a)return;H7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);vqa(this)};
g.h.ai=function(a){this.info("launchWithParams no-op for Cast: "+g.Ng(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.y)(function(){this.Id()},this),(0,g.y)(function(){this.Id(Error("Failed to stop receiver app."))},this)):this.Id(Error("Stopping cast device witout session."))};
g.h.qs=g.Ha;g.h.T=function(){this.info("disposeInternal");g.Sp(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;J7.Ha.T.call(this)};
g.h.iL=function(a,b){if(!this.ea())if(b){var c=x5(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Ng(c));switch(d){case "mdxSessionStatus":I7(this,c.screenId);break;default:H7(this,"Unknown youtube message: "+d)}}else H7(this,"Unable to parse message.")}else H7(this,"No data in message.")};
g.h.Iv=function(a,b,c,d){C7(this.F,this.i.label,a,this.i.friendlyName,(0,g.y)(function(e){e?b(e):0<=d?(H7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Qp((0,g.y)(this.Iv,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.XA=function(){return this.g};
g.h.xM=function(a){this.ea()||a||(H7(this,"Cast session died."),this.Id())};g.A(K7,G7);g.h=K7.prototype;g.h.os=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.ai=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ha;g.Sp(this.A);this.o?this.o.stop((0,g.y)(this.Id,this,null),(0,g.y)(this.Id,this,"Failed to stop DIAL device.")):this.Id()};
g.h.T=function(){this.g();this.g=g.Ha;g.Sp(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;K7.Ha.T.call(this)};
g.h.AM=function(a){this.ea()||a||(H7(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Id())};
g.h.fq=function(a){this.H=H5();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,M7(this));a(b);L7(this)}else this.B=(0,g.y)(function(){g.Sp(this.A);this.B=g.Ha;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,M7(this));a(c);L7(this)},this),this.A=g.Qp((0,g.y)(function(){this.B()},this),100)};
g.h.CD=function(a,b,c){C7(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.y)(function(d){d&&d.token?(this.Zm(d),b(new chrome.cast.DialLaunchResponse(!1))):this.fq(b,c)},this),(0,g.y)(function(d){H7(this,"Failed to get DIAL screen: "+d);
this.fq(b,c)},this))};g.A(N7,G7);N7.prototype.stop=function(){this.Id()};
N7.prototype.os=g.Ha;N7.prototype.ai=function(){g.Sp(this.g);this.g=NaN;var a=J5(this.F.Fd(),this.i.label);a?this.Zm(a):this.Id(Error("No such screen"))};
N7.prototype.T=function(){g.Sp(this.g);this.g=NaN;N7.Ha.T.call(this)};g.A(O7,g.P);g.h=O7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new chrome.cast.ApiConfig(c,(0,g.y)(this.My,this),(0,g.y)(this.SJ,this),d,e);c.customDialLaunchCallback=(0,g.y)(this.cI,this);chrome.cast.initialize(c,(0,g.y)(function(){this.ea()||
(chrome.cast.addReceiverActionListener(this.o),mqa(),this.i.subscribe("onlineScreenChange",(0,g.y)(this.WA,this)),this.l=T7(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.y)(function(f){this.Jb("Failed to set initial custom receivers: "+g.Ng(f))},this)),this.N("yt-remote-cast2-availability-change",R7(this)),b(!0))},this),(0,g.y)(function(f){this.Jb("Failed to initialize API: "+g.Ng(f));
b(!1)},this))};
g.h.JL=function(a,b){Q7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)Q7("Unsetting old screen status: "+this.g.i.friendlyName),S7(this,null)}if(a&&b){if(!this.g){c=J5(this.i.Fd(),a);if(!c){Q7("setConnectedScreenStatus: Unknown screen.");return}var d=P7(this,c);d||(Q7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.y)(function(e){this.Jb("Failed to set initial custom receivers: "+g.Ng(e))},this)));
Q7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);S7(this,new N7(this.i,d),!0)}this.g.qs(b)}else Q7("setConnectedScreenStatus: no screen.")};
g.h.KL=function(a){this.ea()?this.Jb("Setting connection data on disposed cast v2"):this.g?this.g.ai(a):this.Jb("Setting connection data without a session")};
g.h.zM=function(){this.ea()?this.Jb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),S7(this,null)):Q7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.y)(this.My,this),(0,g.y)(this.oK,this))};
g.h.T=function(){this.i.unsubscribe("onlineScreenChange",(0,g.y)(this.WA,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.bb(g.x("yt.mdx.remote.debug.handlers_")||[],f7);g.sf(this.g);O7.Ha.T.call(this)};
g.h.Jb=function(a){j7("Controller",a)};
g.h.Ny=function(a,b){this.g==a&&(b||S7(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.OJ=function(a,b){if(!this.ea())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),Q7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)Q7("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{Q7("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:S7(this,
new N7(this.i,a));break;case chrome.cast.ReceiverType.DIAL:S7(this,new K7(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:S7(this,new J7(this.i,a));break;default:this.Jb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Jb("Stopping receiver w/o session: "+a.friendlyName)}else this.Jb("onReceiverAction_ called without receiver.")};
g.h.cI=function(a){if(this.ea())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Jb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Jb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return Q7("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Jb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);S7(this,new K7(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.y)(b.CD,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.y)(b.fq,b))};
g.h.My=function(a){if(!this.ea()){Q7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)Q7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),S7(this,new J7(this.i,b),!0);else{this.Jb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=J5(this.i.Fd(),c.label);d&&C5(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(Q7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.sf(this.g),this.g=new J7(this.i,b),this.g.subscribe("sessionScreen",(0,g.y)(this.Ny,this,this.g)),this.g.ai(null));this.g.os(a)}}};
g.h.yM=function(){return this.g?this.g.XA():null};
g.h.oK=function(a){this.ea()||(this.Jb("Failed to estabilish a session: "+g.Ng(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&S7(this,null))};
g.h.SJ=function(a){Q7("Receiver availability updated: "+a);if(!this.ea()){var b=R7(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;R7(this)!=b&&this.N("yt-remote-cast2-availability-change",R7(this))}};
g.h.WA=function(){this.ea()||(this.l=T7(this),Q7("Updating custom receivers: "+g.Ng(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.y)(function(){this.Jb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",R7(this)))};
O7.prototype.setLaunchParams=O7.prototype.KL;O7.prototype.setConnectedScreenStatus=O7.prototype.JL;O7.prototype.stopSession=O7.prototype.zM;O7.prototype.getCastSession=O7.prototype.yM;O7.prototype.requestSession=O7.prototype.requestSession;O7.prototype.init=O7.prototype.init;O7.prototype.dispose=O7.prototype.dispose;var b8=[];j8.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";k8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Ge=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
j8.prototype.isAdPlaying=function(){return 1081==this.playerState};
j8.prototype.getDuration=function(){return this.u?this.D+l8(this):this.D};
j8.prototype.clone=function(){return new j8(p8(this))};g.A(s8,g.P);g.h=s8.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,A8(this,"play")):y8(this,"play"),x8(this,1,n8(t8(this))),this.N("remotePlayerChange")):v8(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,A8(this,"pause")):y8(this,"pause"),x8(this,2,n8(t8(this))),this.N("remotePlayerChange")):v8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=t8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,A8(this,"seekTo",{newTime:a}))}else y8(this,"seekTo",{newTime:a});x8(this,3,a);this.N("remotePlayerChange")}else v8(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,A8(this,"stopVideo")):y8(this,"stopVideo");var a=t8(this);a.index=-1;a.videoId="";k8(a);w8(this,a);this.N("remotePlayerChange")}else v8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=t8(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.y)(function(){j7("CP","set receiver volume: "+d)},this),(0,g.y)(function(){this.Jb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.y)(function(){j7("CP","set receiver muted: "+b)},this),(0,g.y)(function(){this.Jb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);y8(this,"setVolume",e)}c.muted=b;c.volume=a;w8(this,c)}else v8(this,g.Qa(this.setVolume,a,b))};
g.h.Wz=function(a,b){if(1==this.g){var c=t8(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Ng(b.style),g.ec(d,c.g));y8(this,"setSubtitlesTrack",d);w8(this,c)}else v8(this,g.Qa(this.Wz,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();y8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=t8(this);d.audioTrackId=c;w8(this,d)}else v8(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=t8(this);c=c||0;var m={videoId:a,currentIndex:c};o8(l,a,c);g.Ca(b)&&(m8(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Ng(k));y8(this,"setPlaylist",m);d||w8(this,l)};
g.h.hn=function(a,b){if(1==this.g){if(a&&b){var c=t8(this);o8(c,a,b);w8(this,c)}y8(this,"previous")}else v8(this,g.Qa(this.hn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=t8(this);o8(c,a,b);w8(this,c)}y8(this,"next")}else v8(this,g.Qa(this.nextVideo,a,b))};
g.h.Vu=function(){1==this.g?y8(this,"dismissAutoplay"):v8(this,this.Vu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}s8.Ha.dispose.call(this)};
g.h.T=function(){u8(this);this.o=null;this.u.clear();r8(this,null);s8.Ha.T.call(this)};
g.h.Zs=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.LJ=function(a,b){this.N(a,b)};
g.h.IH=function(a){if(!a)this.kk(null),r8(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=t8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)j7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,w8(this,b)}};
g.h.kk=function(a){j7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),z8(this),this.N("remotePlayerChange")};
g.h.HH=function(a){a?(z8(this),this.N("remotePlayerChange")):this.kk(null)};
g.h.Js=function(){y8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.UH=function(){var a=f8();a&&r8(this,a)};
g.h.Jb=function(a){j7("CP",a)};g.A(B8,g.P);g.h=B8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Qa.listId=c);this.Qa.videoId=d;this.Qa.index=k||0;this.Qa.state=3;m8(this.Qa,m);this.o="UNSUPPORTED";C8("Connecting with setPlaylist and params: "+g.Ng(l));this.g.connect({method:"setPlaylist",
params:g.Ng(l)},a,P5())}else C8("Connecting without params"),this.g.connect({},a,P5());Cqa(this)};
g.h.dispose=function(){this.ea()||(this.N("beforeDispose"),D8(this,3));B8.Ha.dispose.call(this)};
g.h.T=function(){E8(this);G8(this);F8(this);g.Sp(this.F);this.F=NaN;g.Sp(this.H);this.H=NaN;this.l=null;g.Qr(this.O);this.O.length=0;this.g.dispose();B8.Ha.T.call(this);this.o=this.B=this.i=this.Qa=this.g=null};
g.h.PC=function(){this.A(2)};
g.h.MH=function(){C8("Channel opened");this.M&&(this.M=!1,F8(this),this.P=g.Qp((0,g.y)(function(){C8("Timing out waiting for a screen.");this.A(1)},this),15E3));
dqa(kqa(this.g),this.V)};
g.h.JH=function(){C8("Channel closed");isNaN(this.u)?S5(!0):S5();this.dispose()};
g.h.KH=function(a){S5();isNaN(this.D())?(C8("Channel error: "+a+" without reconnection"),this.dispose()):(this.M=!0,C8("Channel error: "+a+" with reconnection in "+this.D()+" ms"),D8(this,2))};
g.h.LH=function(a){a.params?C8("Received: action="+a.action+", params="+g.Ng(a.params)):C8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=x5(a.params.devices);this.i=(0,g.G)(a,function(c){return new A5(c)});
a=!!g.Wa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Eqa(this,a);break;case "loungeScreenDisconnected":g.cb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
Eqa(this,!1);break;case "remoteConnected":var b=new A5(x5(a.params.device));g.Wa(this.i,function(c){return b?c.id==b.id:!1})||Spa(this.i,b);
break;case "remoteDisconnected":b=new A5(x5(a.params.device));g.cb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Gqa(this,a);break;case "nowPlaying":Iqa(this,a);break;case "onStateChange":Hqa(this,a);break;case "onAdStateChange":Jqa(this,a);break;case "onVolumeChanged":Kqa(this,a);break;case "onSubtitlesTrackChanged":Fqa(this,a);break;case "nowAutoplaying":Lqa(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.B=a.params.videoId||null;this.N("autoplayUpNext",this.B);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":Mqa(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:C8("Unrecognized action: "+a.action)}};
g.h.yL=function(){if(this.l){var a=this.l;this.l=null;this.Qa.videoId!=a&&H8(this,"getNowPlaying")}};
B8.prototype.subscribe=B8.prototype.subscribe;B8.prototype.unsubscribeByKey=B8.prototype.Bf;B8.prototype.ca=function(){var a=3;this.ea()||(a=0,isNaN(this.D())?b7(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
B8.prototype.getProxyState=B8.prototype.ca;B8.prototype.A=function(a){C8("Disconnecting with "+a);E8(this);this.N("beforeDisconnect",a);1==a&&S5();a7(this.g,a);this.dispose()};
B8.prototype.disconnect=B8.prototype.A;B8.prototype.X=function(){var a=this.Qa;this.l&&(a=this.Qa.clone(),o8(a,this.l,a.index));return p8(a)};
B8.prototype.getPlayerContextData=B8.prototype.X;
B8.prototype.ka=function(a){var b=new j8(a);b.videoId&&b.videoId!=this.Qa.videoId&&(this.l=b.videoId,g.Sp(this.F),this.F=g.Qp((0,g.y)(this.yL,this),5E3));var c=[];this.Qa.listId==b.listId&&this.Qa.videoId==b.videoId&&this.Qa.index==b.index||c.push("remoteQueueChange");this.Qa.playerState==b.playerState&&this.Qa.volume==b.volume&&this.Qa.muted==b.muted&&n8(this.Qa)==n8(b)&&g.Ng(this.Qa.g)==g.Ng(b.g)||c.push("remotePlayerChange");this.Qa.reset(a);(0,g.B)(c,function(d){this.N(d)},this)};
B8.prototype.setPlayerContextData=B8.prototype.ka;B8.prototype.R=function(){var a=this.g.A.id,b=g.Wa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
B8.prototype.getOtherConnectedRemoteId=B8.prototype.R;B8.prototype.D=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
B8.prototype.getReconnectTimeout=B8.prototype.D;B8.prototype.aa=function(){return this.o||"UNSUPPORTED"};
B8.prototype.getAutoplayMode=B8.prototype.aa;B8.prototype.Y=function(){return this.B||""};
B8.prototype.getAutoplayVideoId=B8.prototype.Y;B8.prototype.va=function(){if(!isNaN(this.D())){var a=this.g.i;g.po(a.g);a.start()}};
B8.prototype.reconnect=B8.prototype.va;B8.prototype.ia=function(a,b){H8(this,a,b);I8(this)};
B8.prototype.sendMessage=B8.prototype.ia;g.A(J8,n7);g.h=J8.prototype;g.h.Fd=function(a){return this.Gc.$_gs(a)};
g.h.contains=function(a){return!!this.Gc.$_c(a)};
g.h.get=function(a){return this.Gc.$_g(a)};
g.h.start=function(){this.Gc.$_st()};
g.h.add=function(a,b,c){this.Gc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Gc.$_r(a,b,c)};
g.h.Sn=function(a,b,c,d){this.Gc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.i.length;a<b;++a)this.Gc.$_ubk(this.i[a]);this.i.length=0;this.Gc=null;J8.Ha.T.call(this)};
g.h.vM=function(){this.N("screenChange")};
g.h.pJ=function(){this.N("onlineScreenChange")};
A7.prototype.$_st=A7.prototype.start;A7.prototype.$_gspc=A7.prototype.wM;A7.prototype.$_gsppc=A7.prototype.VA;A7.prototype.$_c=A7.prototype.contains;A7.prototype.$_g=A7.prototype.get;A7.prototype.$_a=A7.prototype.add;A7.prototype.$_un=A7.prototype.Sn;A7.prototype.$_r=A7.prototype.remove;A7.prototype.$_gs=A7.prototype.Fd;A7.prototype.$_gos=A7.prototype.UA;A7.prototype.$_s=A7.prototype.subscribe;A7.prototype.$_ubk=A7.prototype.Bf;var K8=null,L8=null,$8=null,P8=[];g.t(a9,g.H);g.h=a9.prototype;
g.h.T=function(){g.H.prototype.T.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.Jy,this);this.g.unsubscribe("remotePlayerChange",this.mk,this);this.g.unsubscribe("remoteQueueChange",this.an,this);this.g.unsubscribe("autoplayUpNext",this.ky,this);this.g.unsubscribe("previousNextChange",this.Gy,this);this.g.unsubscribe("nowAutoplaying",this.Cy,this);this.g.unsubscribe("autoplayDismissed",this.jy,this);this.g=this.u=null};
g.h.jx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(d9(this)){if(!t8(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==t8(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.zj(c[0],c[1]);break;case "control_subtitles_set_track":e9(this,c[0]);break;case "control_set_audio_track":c=c[0],d9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();f9(this,0==c?void 0:c);break;case "control_seek":f9(this,c[0]);break;case "control_subtitles_set_track":e9(this,c[0]);break;case "control_set_audio_track":c=c[0],d9(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.GH=function(a){this.I.LC(a)};
g.h.eM=function(a){this.jx("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.iA=function(){var a=this.i.getOption("captions","track");g.Xb(a)||e9(this,a)};
g.h.yy=function(a){if(d9(this)){this.g.unsubscribe("remotePlayerChange",this.mk,this);var b=Math.round(a.volume);a=!!a.muted;var c=t8(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.mk,this)}};
g.h.GI=function(){g.Xb(this.B)||Yqa(this,this.B);this.D=!1};
g.h.Jy=function(a,b){this.A.stop();2==b&&this.hA()};
g.h.mk=function(){if(d9(this)){this.o.stop();var a=t8(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.pm=1;break;case 1082:case 1083:this.u.pm=0;break;default:this.u.pm=-1}switch(a.playerState){case 1081:case 1:c9(this,new g.$C(8));this.gA();break;case 1085:case 3:c9(this,new g.$C(9));break;case 1083:case 0:c9(this,new g.$C(2));this.H.stop();b9(this,this.i.getVideoData().lengthSeconds);break;case 1084:c9(this,new g.$C(4));break;case 2:c9(this,new g.$C(4));b9(this,n8(a));
break;case -1:c9(this,new g.$C(64));break;case -1E3:c9(this,new g.$C(128,{errorCode:"mdx.remoteerror",message:"This video is not available for remote playback."}))}a=t8(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,Yqa(this,a));a=t8(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.P.isActive()||this.HA()}else Xqa(this)};
g.h.Gy=function(){this.i.N("mdxpreviousnextchange")};
g.h.an=function(){d9(this)||Xqa(this)};
g.h.WB=function(){this.g.Vu()};
g.h.ky=function(a){a&&(a=g.Nq("/watch_queue_ajax",{method:"GET",Cc:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.y)(this.QK,this)}))&&(this.M=(0,g.y)(a.abort,a))};
g.h.QK=function(a,b){var c=new g.dB(g.W(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.Cy=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.jy=function(){this.i.N("mdxautoplaycanceled")};
g.h.mF=function(a,b){-1==t8(this.g).playerState?f9(this,a):b&&this.g.seekTo(a)};
g.h.HA=function(){if(d9(this)){var a=t8(this.g);this.l.Na(this.O);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.O=this.l.K(this.i,"onVolumeChange",this.yy)}};
g.h.gA=function(){this.o.stop();if(!this.g.ea()){var a=t8(this.g);1==a.playerState&&c9(this,new g.$C(8));b9(this,n8(a));this.o.start()}};
g.h.hA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(g9,g.U);g9.prototype.u=function(a){$qa(this,a.state)};g.t(h9,g.IT);h9.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.F=g.sb(a,this.A,this),g.JT(this,(0,g.G)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.me(this.A(a)),this.enable(!0)):this.enable(!1)};
h9.prototype.A=function(a){return a.key};
h9.prototype.le=function(a){return"cast-selector-receiver"==a?"Cast...":this.F[a].name};
h9.prototype.Ic=function(a){g.IT.prototype.Ic.call(this,a);this.l.setOption("remote","currentReceiver",this.F[a]);this.o.gb()};g.t(i9,g.FK);g.h=i9.prototype;g.h.create=function(){Rqa(g.Wy(g.W(this.player)));this.u.push(g.Xp("yt-remote-before-disconnect",this.DH,this));this.u.push(g.Xp("yt-remote-connection-change",this.TJ,this));this.u.push(g.Xp("yt-remote-receiver-availability-change",this.Hy,this));this.u.push(g.Xp("yt-remote-auto-connect",this.RJ,this));this.u.push(g.Xp("yt-remote-receiver-resumed",this.QJ,this));this.Hy()};
g.h.load=function(){this.player.cancelPlayback();g.FK.prototype.load.call(this);this.o=new a9(this,this.player,this.g);var a=(a=Wqa())?a.currentTime:0;var b=Z8()?new s8(U8(),void 0):null;0==a&&b&&(a=n8(t8(b)));0!=a&&this.nd(a);Zqa(this,this.Xj,this.Xj);g.JX(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.tf(this.o,this.g);this.g=this.o=null;g.FK.prototype.unload.call(this);g.JX(this.player.app,5)};
g.h.T=function(){g.Yp(this.u);g.FK.prototype.T.call(this)};
g.h.Re=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.o.jx.apply(this.o,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.pm};
g.h.HC=function(){return this.loaded?this.o.suggestion:null};
g.h.Ge=function(){return this.g?t8(this.g).Ge:!1};
g.h.hasNext=function(){return this.g?t8(this.g).hasNext:!1};
g.h.nd=function(a,b){this.D=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.D};
g.h.getProgressState=function(){var a=t8(this.g),b=this.player.getVideoData();return{allowSeeking:g.R(g.W(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.fc():!a.isAdPlaying()&&this.player.fc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+l8(a):a.l,isAtLiveHead:1>=(a.u?a.i+l8(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+l8(a):a.i,seekableStart:0<a.o?a.o+
l8(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.hn=function(){this.g&&this.g.hn()};
g.h.DH=function(a){1==a&&(this.B=this.g?t8(this.g):null)};
g.h.TJ=function(){var a=Z8()?new s8(U8(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.B=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.sf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.B)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,n8(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Hy=function(){this.A=[this.i].concat(Tqa());var a=V8()||this.i;j9(this,a);this.player.ma("onMdxReceiversChange")};
g.h.RJ=function(){var a=V8();j9(this,a)};
g.h.QJ=function(){this.l=V8()};
g.h.ac=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.A;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?h8():j9(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.A.length&&"cast-selector-receiver"==this.A[1].key?(b&&h8(),!0):!1}};
g.h.Js=function(){this.g.Js()};
g.h.Mb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.ZU.remote=i9;})(_yt_player);
